name: AF_Detect_New
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - absl-py=2.3.1=pyhd8ed1ab_0
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.13.2=py310h5541b7b_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - astunparse=1.6.3=pyhd8ed1ab_3
  - async-timeout=5.0.1=pyhd8ed1ab_1
  - attrs=25.4.0=pyh71513ae_0
  - blinker=1.9.0=pyhff2d567_0
  - brotli-python=1.2.0=py310h8cfb67f_0
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=6.2.1=pyhd8ed1ab_0
  - certifi=2025.10.5=pyhd8ed1ab_0
  - cffi=1.17.1=py310h8deb56e_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.0=pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - cryptography=46.0.3=py310hed992bd_0
  - cuda-crt-tools=12.9.86=ha770c72_2
  - cuda-cudart=12.9.79=h5888daf_0
  - cuda-cudart_linux-64=12.9.79=h3f2d84a_0
  - cuda-nvcc-tools=12.9.86=he02047a_2
  - cuda-nvrtc=12.9.86=hecca717_1
  - cuda-nvtx=12.9.79=hecca717_1
  - cuda-nvvm-tools=12.9.86=h4bc722e_2
  - cuda-version=12.9=h4f385c5_3
  - cudnn=8.9.7.29=h092f7fd_3
  - expat=2.7.1=h6a678d5_0
  - flatbuffers=23.5.26=h59595ed_1
  - frozenlist=1.7.0=py310h9548a50_0
  - gast=0.6.0=pyhd8ed1ab_0
  - giflib=5.2.2=hd590300_0
  - google-auth=2.42.0=pyhd8ed1ab_0
  - google-auth-oauthlib=1.2.2=pyhd8ed1ab_0
  - google-pasta=0.2.0=pyhd8ed1ab_2
  - grpcio=1.59.3=py310h1b8f574_0
  - h2=4.3.0=pyhcf101f3_0
  - h5py=3.15.1=nompi_py310h4aa865e_100
  - hdf5=1.14.6=nompi_h6e4c0c1_103
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=73.2=h59595ed_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - joblib=1.5.2=pyhd8ed1ab_0
  - keras=2.15.0=pyhd8ed1ab_0
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libabseil=20230802.1=cxx17_h59595ed_0
  - libaec=1.1.4=h3f801dc_0
  - libblas=3.9.0=38_h4a7cf45_openblas
  - libcblas=3.9.0=38_h0358290_openblas
  - libcublas=12.9.1.4=h676940d_1
  - libcufft=11.4.1.4=hecca717_1
  - libcurand=10.3.10.19=h676940d_1
  - libcurl=8.16.0=h4e3cde8_0
  - libcusolver=11.7.5.82=h676940d_2
  - libcusparse=12.5.10.65=hecca717_2
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgfortran=15.2.0=h69a702a_7
  - libgfortran5=15.2.0=hcd61629_7
  - libgomp=15.2.0=h767d61c_7
  - libgrpc=1.59.3=hd6c4280_0
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - liblapack=3.9.0=38_h47877c9_openblas
  - libnghttp2=1.67.0=had1ee68_0
  - libnsl=2.0.0=h5eee18b_0
  - libnvjitlink=12.9.86=hecca717_2
  - libopenblas=0.3.30=pthreads_h94d23a6_3
  - libpng=1.6.50=h421ea60_1
  - libprotobuf=4.24.4=hf27288f_0
  - libre2-11=2023.09.01=h7a70373_1
  - libsqlite=3.50.4=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - markdown=3.9=pyhd8ed1ab_0
  - markupsafe=3.0.3=py310h3406613_0
  - ml_dtypes=0.2.0=py310hcc13569_2
  - multidict=6.6.3=py310h89163eb_0
  - nccl=2.28.7.1=h4d09622_0
  - ncurses=6.5=h7934f7d_0
  - numpy=1.26.4=py310hb13e2d6_0
  - oauthlib=3.3.1=pyhd8ed1ab_0
  - openssl=3.5.4=h26f9b46_0
  - opt_einsum=3.4.0=pyhd8ed1ab_1
  - packaging=25.0=pyh29332c3_1
  - pip=25.2=pyhc872135_1
  - propcache=0.3.1=py310h89163eb_0
  - protobuf=4.24.4=py310h620c231_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pyasn1=0.6.1=pyhd8ed1ab_2
  - pyasn1-modules=0.4.2=pyhd8ed1ab_0
  - pycparser=2.22=pyh29332c3_1
  - pyjwt=2.10.1=pyhd8ed1ab_0
  - pyopenssl=25.3.0=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.10.19=h6fa692b_0
  - python-flatbuffers=25.9.23=pyh1e1bc0e_0
  - python_abi=3.10=2_cp310
  - pyu2f=0.1.5=pyhd8ed1ab_1
  - re2=2023.09.01=h7f4b329_1
  - readline=8.3=hc2a1206_0
  - requests=2.32.5=pyhd8ed1ab_0
  - requests-oauthlib=2.0.0=pyhd8ed1ab_1
  - rsa=4.9.1=pyhd8ed1ab_0
  - scikit-learn=1.7.2=py310h228f341_0
  - scipy=1.15.2=py310h1d65ade_0
  - setuptools=80.9.0=py310h06a4308_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.1.10=hdb0a2a9_1
  - sqlite=3.50.2=hb25bd0a_1
  - tensorboard=2.15.2=pyhd8ed1ab_0
  - tensorboard-data-server=0.7.0=py310hed992bd_3
  - tensorflow=2.15.0=cuda120py310h9360858_3
  - tensorflow-base=2.15.0=cuda120py310heceb7ac_3
  - tensorflow-estimator=2.15.0=cuda120py310h549c77d_3
  - termcolor=3.2.0=pyhd8ed1ab_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.15=h54e0aa7_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - werkzeug=3.1.3=pyhd8ed1ab_1
  - wheel=0.45.1=py310h06a4308_0
  - wrapt=1.14.1=py310h5764c6d_1
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yarl=1.22.0=py310h3406613_0
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb25bd0a_0
  - zstandard=0.25.0=py310h139afa4_0
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - contourpy==1.3.2
      - cycler==0.12.1
      - fonttools==4.60.1
      - kiwisolver==1.4.9
      - matplotlib==3.10.7
      - pandas==2.3.3
      - pillow==12.0.0
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - seaborn==0.13.2
      - tensorflow-addons==0.22.0
      - typeguard==2.13.3
      - tzdata==2025.2
prefix: /home/mhuang25/miniconda3/envs/AF_Detect_New
